"""Base de conhecimento de modelagem de ameaças STRIDE — tipos de componente, ameaças e contramedidas."""

from typing import Dict, List


COMPONENT_TYPES = {
    "user": "Usuário final ou ator externo que interage com o sistema",
    "web_server": "Servidor web HTTP/HTTPS que serve conteúdo",
    "api_gateway": "API Gateway que gerencia e roteia requisições de API",
    "load_balancer": "Load balancer que distribui tráfego entre servidores",
    "application_server": "Servidor de aplicação backend que processa a lógica de negócio",
    "database": "Banco de dados relacional ou NoSQL armazenando dados",
    "cache": "Camada de cache em memória (Redis, ElastiCache, Memcached)",
    "message_queue": "Broker de mensagens para comunicação assíncrona (SQS, RabbitMQ, Kafka)",
    "authentication_service": "Serviço de autenticação e autorização (OAuth, SSO, IAM)",
    "cdn": "Content Delivery Network para distribuição de arquivos estáticos",
    "firewall": "Firewall de rede ou WAF filtrando tráfego",
    "storage": "Serviço de armazenamento de arquivos/objetos (S3, Blob, GCS)",
    "microservice": "Microsserviço individual em uma arquitetura distribuída",
    "container": "Workload conteinerizado (Docker, pod Kubernetes)",
    "function": "Função serverless (Lambda, Azure Functions)",
    "network": "Limite de rede, VPC, subnet ou DMZ",
    "external_service": "Ponto de integração de terceiros ou externo",
    "monitoring": "Serviço de monitoramento, logging ou observabilidade",
    "dns": "Serviço DNS para resolução de nomes",
    "vpn": "Endpoint de VPN ou túnel privado",
}

COMPONENT_TYPE_KEYWORDS = {
    "user": ["user", "client", "browser", "developer", "admin", "actor", "person", "operator"],
    "web_server": ["web server", "nginx", "apache", "iis", "httpd", "http server"],
    "api_gateway": ["api gateway", "api management", "apigee", "kong", "api manager", "gateway"],
    "load_balancer": ["load balancer", "alb", "elb", "nlb", "application load", "balancer"],
    "application_server": ["app server", "application server", "backend", "server", "sei", "sip", "application"],
    "database": ["database", "rds", "mysql", "postgres", "mongodb", "dynamodb", "sql", "nosql", "db"],
    "cache": ["cache", "redis", "elasticache", "memcached", "in-memory"],
    "message_queue": ["queue", "sqs", "sns", "kafka", "rabbitmq", "message broker", "pubsub"],
    "authentication_service": ["auth", "authentication", "iam", "sso", "oauth", "microsoft entra", "entra", "identity", "ad", "active directory"],
    "cdn": ["cdn", "cloudfront", "cloudflare", "fastly", "akamai", "content delivery"],
    "firewall": ["firewall", "waf", "shield", "ddos", "security group", "aws waf", "aws shield"],
    "storage": ["storage", "s3", "blob", "efs", "nfs", "file system", "object storage", "elastic file"],
    "microservice": ["microservice", "service", "logic app", "workflow"],
    "container": ["container", "docker", "kubernetes", "k8s", "ecs", "pod"],
    "function": ["lambda", "function", "serverless", "azure function", "cloud function"],
    "network": ["vpc", "vnet", "subnet", "network", "availability zone", "private subnet", "public subnet", "resource group"],
    "external_service": ["saas", "rest", "soap", "third-party", "external", "web service", "azure services"],
    "monitoring": ["cloudwatch", "monitoring", "logging", "cloudtrail", "audit", "log", "alerting"],
    "dns": ["dns", "route53", "name server"],
    "vpn": ["vpn", "tunnel", "private connection", "expressroute"],
}

STRIDE_CATEGORIES = {
    "S": {
        "name": "Spoofing",
        "description": "Se passar por outra pessoa ou sistema",
        "property_violated": "Autenticação",
        "color": "#e74c3c",
    },
    "T": {
        "name": "Tampering",
        "description": "Modificar dados ou código",
        "property_violated": "Integridade",
        "color": "#e67e22",
    },
    "R": {
        "name": "Repudiation",
        "description": "Negar ter realizado uma ação",
        "property_violated": "Não-repúdio",
        "color": "#f1c40f",
    },
    "I": {
        "name": "Information Disclosure",
        "description": "Expor informações a partes não autorizadas",
        "property_violated": "Confidencialidade",
        "color": "#3498db",
    },
    "D": {
        "name": "Denial of Service",
        "description": "Negar ou degradar o serviço aos usuários",
        "property_violated": "Disponibilidade",
        "color": "#9b59b6",
    },
    "E": {
        "name": "Elevation of Privilege",
        "description": "Obter capacidades sem autorização",
        "property_violated": "Autorização",
        "color": "#27ae60",
    },
}

COMPONENT_STRIDE_THREATS: Dict[str, List[dict]] = {
    "user": [
        {
            "stride_letter": "S",
            "description": "Atacante se passa por um usuário legítimo para acessar o sistema",
            "severity": "High",
            "attack_vector": "Roubo de credenciais, phishing, sequestro de sessão",
            "vulnerability": "Autenticação fraca, reuso de senha, ausência de MFA",
            "countermeasure": "Implementar autenticação multifator (MFA), impor políticas de senha forte, usar FIDO2/WebAuthn",
            "cwe_reference": "CWE-287",
        },
        {
            "stride_letter": "R",
            "description": "Usuário nega ter realizado uma ação sensível (ex.: transação, alteração de dados)",
            "severity": "Medium",
            "attack_vector": "Ausência de trilhas de auditoria, ações não assinadas",
            "vulnerability": "Falta de logging de auditoria, sem assinaturas digitais",
            "countermeasure": "Implementar logging de auditoria centralizado à prova de adulteração, usar assinaturas digitais para ações críticas",
            "cwe_reference": "CWE-778",
        },
        {
            "stride_letter": "I",
            "description": "Dados pessoais ou token de sessão do usuário são expostos",
            "severity": "High",
            "attack_vector": "Ataque man-in-the-middle, armazenamento inseguro de tokens",
            "vulnerability": "Canais não criptografados, armazenamento local inseguro",
            "countermeasure": "Impor HTTPS/TLS em tudo, armazenar tokens em cookies seguros httpOnly, implementar rotação de token",
            "cwe_reference": "CWE-311",
        },
    ],
    "web_server": [
        {
            "stride_letter": "T",
            "description": "Atacante modifica respostas HTTP ou injeta conteúdo malicioso (XSS, injeção de resposta)",
            "severity": "High",
            "attack_vector": "Cross-site scripting (XSS), HTTP response splitting",
            "vulnerability": "Falta de codificação de saída, ausência de Content Security Policy",
            "countermeasure": "Implementar Content Security Policy (CSP) estrita, codificar toda saída de usuário, usar cabeçalhos de segurança (X-Frame-Options, HSTS)",
            "cwe_reference": "CWE-79",
        },
        {
            "stride_letter": "D",
            "description": "Servidor web sobrecarregado por ataque DDoS, ficando indisponível",
            "severity": "High",
            "attack_vector": "DDoS volumétrico, HTTP flood, ataque Slowloris",
            "vulnerability": "Sem rate limiting, sem camada de proteção anti-DDoS",
            "countermeasure": "Usar WAF e proteção anti-DDoS (CloudFlare, AWS Shield), implementar rate limiting e throttling de conexões",
            "cwe_reference": "CWE-400",
        },
        {
            "stride_letter": "I",
            "description": "Arquivos de configuração, stack traces ou dados sensíveis expostos via páginas de erro ou listagem de diretório",
            "severity": "Medium",
            "attack_vector": "Forced browsing, análise de mensagens de erro",
            "vulnerability": "Mensagens de erro verbosas, listagem de diretório habilitada, servidor mal configurado",
            "countermeasure": "Desabilitar listagem de diretório, usar páginas de erro genéricas, remover cabeçalhos de versão do servidor",
            "cwe_reference": "CWE-200",
        },
        {
            "stride_letter": "E",
            "description": "Atacante explora vulnerabilidade do servidor web para obter privilégios elevados no SO",
            "severity": "Critical",
            "attack_vector": "Execução remota de código via CVE não corrigido, exploração de upload de arquivos",
            "vulnerability": "Software de servidor desatualizado, tratamento inseguro de upload de arquivos",
            "countermeasure": "Manter o software do servidor atualizado, aplicar execução com privilégio mínimo, usar isolamento por container",
            "cwe_reference": "CWE-269",
        },
    ],
    "api_gateway": [
        {
            "stride_letter": "S",
            "description": "Atacante forja tokens ou chaves de API para acessar endpoints protegidos",
            "severity": "Critical",
            "attack_vector": "Roubo de chave de API, forja de JWT, abuso de token OAuth",
            "vulnerability": "Validação de token fraca, armazenamento inseguro de chaves, ausência de verificação de assinatura",
            "countermeasure": "Validar assinaturas JWT, usar tokens de curta duração com rotação via refresh, implementar escopo de chaves de API",
            "cwe_reference": "CWE-347",
        },
        {
            "stride_letter": "T",
            "description": "Atacante intercepta e modifica requisições de API em trânsito",
            "severity": "High",
            "attack_vector": "Ataque man-in-the-middle em chamadas de API",
            "vulnerability": "Ausência de TLS, sem assinatura de requisição/resposta",
            "countermeasure": "Impor TLS 1.2+ em todo tráfego de API, implementar assinatura de requisições (HMAC), usar mTLS entre serviços",
            "cwe_reference": "CWE-319",
        },
        {
            "stride_letter": "D",
            "description": "API sobrecarregada por excesso de requisições (flooding de API)",
            "severity": "High",
            "attack_vector": "Abuso de API, ataques de bots, scraping em larga escala",
            "vulnerability": "Ausência de rate limiting, sem políticas de throttling",
            "countermeasure": "Implementar rate limiting e gestão de cotas por chave de API/usuário, usar throttling no gateway",
            "cwe_reference": "CWE-770",
        },
        {
            "stride_letter": "E",
            "description": "Falha de autorização em nível de objeto (BOLA/IDOR) permite acesso a recursos de outros usuários",
            "severity": "Critical",
            "attack_vector": "Manipulação de IDs de objeto em requisições de API (IDOR/BOLA — OWASP API #1)",
            "vulnerability": "Ausência de verificação de autorização em nível de recurso",
            "countermeasure": "Implementar verificação de autorização em nível de objeto, usar referências indiretas, impor validação de propriedade",
            "cwe_reference": "CWE-639",
        },
    ],
    "load_balancer": [
        {
            "stride_letter": "T",
            "description": "Atacante manipula regras de roteamento para redirecionar tráfego a backends maliciosos",
            "severity": "High",
            "attack_vector": "Roteamento mal configurado, envenenamento de DNS",
            "vulnerability": "Interface administrativa desprotegida, sem verificação de integridade das regras de roteamento",
            "countermeasure": "Restringir acesso administrativo ao plano de gerência, impor configuração via IaC, habilitar auditoria de mudanças",
            "cwe_reference": "CWE-601",
        },
        {
            "stride_letter": "D",
            "description": "Load balancer se torna ponto único de falha sob ataque intenso",
            "severity": "High",
            "attack_vector": "DDoS direcionado ao load balancer, esgotamento da tabela de sessões",
            "vulnerability": "Instância única de load balancer, sem auto-scaling",
            "countermeasure": "Implantar load balancers em pares HA entre zonas de disponibilidade, usar anycast para distribuição global",
            "cwe_reference": "CWE-400",
        },
        {
            "stride_letter": "I",
            "description": "Terminação de TLS no load balancer expõe tráfego em texto claro na rede interna",
            "severity": "Medium",
            "attack_vector": "Sniffing de rede interna após a terminação de TLS",
            "vulnerability": "Terminação de TLS sem recriptografia até os backends",
            "countermeasure": "Usar TLS de ponta a ponta ou TLS passthrough, criptografar o tráfego interno entre load balancer e backends",
            "cwe_reference": "CWE-311",
        },
    ],
    "application_server": [
        {
            "stride_letter": "T",
            "description": "Injeção SQL/NoSQL permite ao atacante modificar consultas e dados do banco",
            "severity": "Critical",
            "attack_vector": "Injeção SQL, injeção de comando via entrada de usuário não sanitizada",
            "vulnerability": "Construção dinâmica de queries com entrada de usuário, ausência de queries parametrizadas",
            "countermeasure": "Usar queries parametrizadas/prepared statements, implementar ORM com binding de query, aplicar validação de entrada",
            "cwe_reference": "CWE-89",
        },
        {
            "stride_letter": "E",
            "description": "Deserialização insegura leva à execução remota de código",
            "severity": "Critical",
            "attack_vector": "Objetos serializados manipulados em payloads de API",
            "vulnerability": "Deserialização de dados não confiáveis sem verificação de integridade",
            "countermeasure": "Evitar deserialização de dados não confiáveis, usar allow-lists para deserialização, implementar verificação de integridade",
            "cwe_reference": "CWE-502",
        },
        {
            "stride_letter": "I",
            "description": "Dados sensíveis vazam por logs verbosos ou endpoints de debug deixados em produção",
            "severity": "Medium",
            "attack_vector": "Injeção de log, endpoints de debug expostos, SSRF",
            "vulnerability": "Modo debug em produção, PII em logs, vulnerabilidades de SSRF",
            "countermeasure": "Desabilitar o modo debug em produção, remover PII dos logs, bloquear SSRF protegendo o endpoint de metadados",
            "cwe_reference": "CWE-532",
        },
        {
            "stride_letter": "D",
            "description": "Aplicação consome recursos sem limite devido a ataque de complexidade algorítmica (ReDoS, zip bomb)",
            "severity": "Medium",
            "attack_vector": "ReDoS (negação de serviço via regex), uploads de payload grandes, zip bombs",
            "vulnerability": "Regex sem limite, ausência de limites de tamanho de payload",
            "countermeasure": "Definir limites de tamanho de payload, usar bibliotecas de regex seguras, implementar circuit breakers",
            "cwe_reference": "CWE-407",
        },
    ],
    "database": [
        {
            "stride_letter": "T",
            "description": "Atacante modifica ou apaga dados diretamente no banco de dados",
            "severity": "Critical",
            "attack_vector": "Injeção SQL, acesso direto não autorizado ao banco",
            "vulnerability": "Porta do banco exposta, contas de aplicação com privilégios excessivos",
            "countermeasure": "Restringir o banco a subnets privadas, usar contas de banco com privilégio mínimo, habilitar segurança em nível de linha",
            "cwe_reference": "CWE-89",
        },
        {
            "stride_letter": "I",
            "description": "Dump do banco expõe dados sensíveis de clientes (PII, credenciais, dados financeiros)",
            "severity": "Critical",
            "attack_vector": "Exfiltração de dados via injeção SQL, roubo de backup, acesso mal configurado",
            "vulnerability": "Armazenamento não criptografado, políticas de IAM excessivamente permissivas, backups não criptografados",
            "countermeasure": "Habilitar criptografia em repouso e em trânsito, implementar criptografia em nível de coluna para PII, restringir acesso a backups",
            "cwe_reference": "CWE-312",
        },
        {
            "stride_letter": "D",
            "description": "Banco de dados indisponível por esgotamento de recursos ou ataque de ransomware",
            "severity": "High",
            "attack_vector": "Esgotamento do pool de conexões, ransomware criptografando os arquivos de dados",
            "vulnerability": "Sem limites de conexão, retenção de backup desprotegida",
            "countermeasure": "Definir limites no pool de conexões, implementar backups com PITR, usar Multi-AZ para alta disponibilidade",
            "cwe_reference": "CWE-400",
        },
        {
            "stride_letter": "E",
            "description": "Usuário do banco escala privilégios para DBA/root explorando stored procedures",
            "severity": "High",
            "attack_vector": "Exploração de stored procedures com EXECUTE AS, injeção de UDF",
            "vulnerability": "Usuários do banco com privilégios excessivos, stored procedures não auditadas",
            "countermeasure": "Aplicar privilégio mínimo para todas as contas do banco, auditar todas as stored procedures, desabilitar xp_cmdshell",
            "cwe_reference": "CWE-269",
        },
        {
            "stride_letter": "R",
            "description": "Alterações no banco realizadas sem trilha de auditoria, impedindo investigação forense",
            "severity": "Medium",
            "attack_vector": "Ameaça interna, alterações de schema/dados não rastreadas",
            "vulnerability": "Falta de logging de auditoria, sem captura de mudança de dados",
            "countermeasure": "Habilitar logging de auditoria do banco, usar CDC (Change Data Capture), armazenar logs em storage imutável",
            "cwe_reference": "CWE-778",
        },
    ],
    "cache": [
        {
            "stride_letter": "T",
            "description": "Ataque de cache poisoning injeta dados maliciosos no cache, servidos a usuários legítimos",
            "severity": "High",
            "attack_vector": "HTTP response splitting, manipulação de chave de cache",
            "vulnerability": "Construção incorreta da chave de cache, ausência de validação do cache",
            "countermeasure": "Usar políticas estritas de chave de cache, validar entradas do cache, implementar cache-busting para dados sensíveis",
            "cwe_reference": "CWE-349",
        },
        {
            "stride_letter": "I",
            "description": "Dados sensíveis armazenados em cache em texto claro e acessíveis a serviços não autorizados",
            "severity": "High",
            "attack_vector": "Acesso não autorizado ao Redis/Memcached sem autenticação",
            "vulnerability": "Cache exposto sem autenticação (configuração padrão do Redis), sem isolamento de rede",
            "countermeasure": "Habilitar autenticação (AUTH) do Redis, vincular apenas a interfaces privadas, evitar cachear dados sensíveis sem criptografia",
            "cwe_reference": "CWE-312",
        },
        {
            "stride_letter": "D",
            "description": "Cache stampede sobrecarrega o backend quando o cache expira simultaneamente",
            "severity": "Medium",
            "attack_vector": "Thundering herd, ataques de invalidação de cache",
            "vulnerability": "Sem lock/mutex de cache, expiração simultânea de chaves quentes",
            "countermeasure": "Implementar padrão de lock/mutex de cache, usar expiração antecipada probabilística, definir TTLs escalonados",
            "cwe_reference": "CWE-400",
        },
    ],
    "message_queue": [
        {
            "stride_letter": "T",
            "description": "Atacante injeta mensagens maliciosas na fila para manipular o processamento posterior",
            "severity": "High",
            "attack_vector": "Injeção de mensagem via produtor comprometido, ataques de replay",
            "vulnerability": "Ausência de verificação de integridade da mensagem, sem autenticação de produtores",
            "countermeasure": "Assinar mensagens com HMAC/assinaturas digitais, validar esquemas de mensagem, implementar dead-letter queues",
            "cwe_reference": "CWE-20",
        },
        {
            "stride_letter": "R",
            "description": "Remetente nega ter publicado uma mensagem, sem prova de origem",
            "severity": "Medium",
            "attack_vector": "Negação de entrega de mensagem em fluxos financeiros/de compliance",
            "vulnerability": "Sem assinatura de mensagem, ausência de IDs de correlação",
            "countermeasure": "Usar assinatura de mensagem com chaves assimétricas, implementar recibos de mensagem, habilitar trilha de auditoria",
            "cwe_reference": "CWE-778",
        },
        {
            "stride_letter": "D",
            "description": "Fila inundada com mensagens poison-pill causando falhas nos consumidores (DoS)",
            "severity": "High",
            "attack_vector": "Flooding de mensagens, padrão poison-pill",
            "vulnerability": "Sem rate limiting na ingestão de mensagens, ausência de dead-letter queue",
            "countermeasure": "Implementar dead-letter queues, definir limites de tamanho/taxa de mensagens, usar circuit breakers nos consumidores",
            "cwe_reference": "CWE-400",
        },
        {
            "stride_letter": "I",
            "description": "Mensagens em trânsito contêm payload sensível sem criptografia",
            "severity": "High",
            "attack_vector": "Sniffing de rede, inscrição não autorizada de listener na fila",
            "vulnerability": "Payloads de mensagem não criptografados, sem controle de acesso nas inscrições da fila",
            "countermeasure": "Criptografar payloads de mensagem em nível de aplicação, restringir acesso à fila via políticas de IAM",
            "cwe_reference": "CWE-311",
        },
    ],
    "authentication_service": [
        {
            "stride_letter": "S",
            "description": "Atacante contorna a autenticação via má configuração de OAuth/SAML ou forja de token",
            "severity": "Critical",
            "attack_vector": "Abuso do fluxo implícito de OAuth, forja de asserção SAML, confusão de algoritmo JWT (alg:none)",
            "vulnerability": "Fluxos OAuth mal configurados, validação SAML fraca, aceitação de JWTs não assinados",
            "countermeasure": "Usar PKCE no OAuth, validar todas as asserções SAML, impor assinatura JWT RS256/ES256, rejeitar alg:none",
            "cwe_reference": "CWE-287",
        },
        {
            "stride_letter": "E",
            "description": "Escalonamento de privilégio via manipulação de escopo ou vulnerabilidade na atribuição de papéis",
            "severity": "Critical",
            "attack_vector": "Elevação de escopo no OAuth, mass assignment no perfil do usuário, forced browsing a endpoints administrativos",
            "vulnerability": "Validação de escopo inadequada, vulnerabilidade de mass assignment no objeto de usuário",
            "countermeasure": "Validar escopos no servidor a cada requisição, usar allowlists para atribuição de papéis, implementar ABAC/RBAC",
            "cwe_reference": "CWE-269",
        },
        {
            "stride_letter": "D",
            "description": "Serviço de autenticação indisponível por ataque de credential stuffing ou falha de infraestrutura",
            "severity": "High",
            "attack_vector": "Credential stuffing, força bruta causando bloqueio de contas, DDoS na infraestrutura",
            "vulnerability": "Sem limites de bloqueio, sem proteção contra bots, instância única de autenticação",
            "countermeasure": "Implementar bloqueio de conta com CAPTCHA, usar CAPTCHA em falhas de login, implantar autenticação em configuração HA",
            "cwe_reference": "CWE-307",
        },
        {
            "stride_letter": "I",
            "description": "Credenciais ou tokens expostos em logs, URLs ou mensagens de erro",
            "severity": "High",
            "attack_vector": "Análise de log, vazamento por cabeçalho referrer, endpoints de debug",
            "vulnerability": "Logging de dados sensíveis, passagem de credenciais em parâmetros de URL",
            "countermeasure": "Nunca logar credenciais/tokens, passar tokens via cabeçalhos e não URLs, remover PII de todos os logs",
            "cwe_reference": "CWE-532",
        },
    ],
    "cdn": [
        {
            "stride_letter": "T",
            "description": "Cache poisoning na CDN serve conteúdo malicioso globalmente",
            "severity": "High",
            "attack_vector": "Injeção via cabeçalho HTTP Host, manipulação de chave de cache",
            "vulnerability": "Normalização incorreta da chave de cache, ausência de validação do cache",
            "countermeasure": "Configurar chaves de cache estritas, implementar cabeçalhos Vary, usar cache-control no-store para páginas sensíveis",
            "cwe_reference": "CWE-349",
        },
        {
            "stride_letter": "D",
            "description": "Servidores de origem da CDN sobrecarregados quando a CDN é contornada",
            "severity": "Medium",
            "attack_vector": "Ataque direto ao IP de origem após descoberta do IP da CDN",
            "vulnerability": "IP de origem exposto, sem firewall de origem para restringir tráfego que não venha da CDN",
            "countermeasure": "Restringir a origem apenas aos ranges de IP da CDN, rotacionar/ocultar o IP de origem, implementar origin shield",
            "cwe_reference": "CWE-400",
        },
    ],
    "firewall": [
        {
            "stride_letter": "T",
            "description": "Regras de firewall mal configuradas permitem tráfego não autorizado",
            "severity": "Critical",
            "attack_vector": "Regra mal configurada, drift de infraestrutura, regras 0.0.0.0/0 excessivamente permissivas",
            "vulnerability": "Gestão manual de regras, ausência de aplicação via infrastructure-as-code",
            "countermeasure": "Usar IaC para todas as regras de firewall, impor acesso de rede com privilégio mínimo, auditar grupos de segurança regularmente",
            "cwe_reference": "CWE-183",
        },
        {
            "stride_letter": "E",
            "description": "Atacante contorna o WAF usando técnicas de encoding para atingir o backend vulnerável",
            "severity": "High",
            "attack_vector": "Bypass de WAF via encoding Unicode, double encoding, HTTP parameter pollution",
            "vulnerability": "Regras de WAF baseadas em regex sem normalização, cobertura de regras incompleta",
            "countermeasure": "Usar grupos de regras gerenciadas de WAF, normalizar a entrada antes da avaliação do WAF, manter as regras do WAF atualizadas",
            "cwe_reference": "CWE-20",
        },
    ],
    "storage": [
        {
            "stride_letter": "I",
            "description": "Bucket de armazenamento publicamente acessível expõe arquivos sensíveis",
            "severity": "Critical",
            "attack_vector": "Enumeração de bucket S3, ACL pública mal configurada",
            "vulnerability": "Políticas de bucket públicas, ausência da configuração Block Public Access",
            "countermeasure": "Habilitar Block Public Access, usar políticas de bucket para negar acesso público, habilitar criptografia server-side do S3",
            "cwe_reference": "CWE-312",
        },
        {
            "stride_letter": "T",
            "description": "Atacante sobrescreve ou apaga arquivos críticos no armazenamento",
            "severity": "High",
            "attack_vector": "Role de IAM com privilégio excessivo (s3:DeleteObject), ransomware",
            "vulnerability": "Acesso ao armazenamento com privilégio excessivo, ausência de versionamento e MFA delete",
            "countermeasure": "Habilitar versionamento de objetos com MFA delete, usar IAM com privilégio mínimo, implementar S3 Object Lock para compliance",
            "cwe_reference": "CWE-732",
        },
        {
            "stride_letter": "D",
            "description": "Armazenamento indisponível por exclusão acidental ou ransomware",
            "severity": "High",
            "attack_vector": "`rm -rf` acidental, criptografia por ransomware do sistema de arquivos compartilhado",
            "vulnerability": "Sem estratégia de backup, sem soft-delete ou versionamento",
            "countermeasure": "Habilitar versionamento e replicação entre regiões, implementar backups automatizados com testes de restauração",
            "cwe_reference": "CWE-400",
        },
    ],
    "microservice": [
        {
            "stride_letter": "S",
            "description": "Atacante se passa por um serviço interno confiável para fazer chamadas não autorizadas",
            "severity": "High",
            "attack_vector": "Ausência de autenticação serviço-a-serviço, credenciais de serviço roubadas",
            "vulnerability": "Serviços aceitando chamadas de qualquer IP interno sem autenticação",
            "countermeasure": "Implementar TLS mútuo (mTLS) na comunicação entre serviços, usar service mesh com identidade (Istio/Linkerd)",
            "cwe_reference": "CWE-287",
        },
        {
            "stride_letter": "T",
            "description": "Microsserviço malicioso na malha injeta respostas adulteradas",
            "severity": "High",
            "attack_vector": "Sidecar proxy comprometido, ataque de supply chain na imagem do serviço",
            "vulnerability": "Imagens de container não assinadas, falta de aplicação de política de rede",
            "countermeasure": "Assinar todas as imagens de container (Cosign/Notary), impor políticas de rede, usar service mesh para criptografar o tráfego",
            "cwe_reference": "CWE-829",
        },
        {
            "stride_letter": "D",
            "description": "Falhas em cascata entre microsserviços por ausência de circuit breakers",
            "severity": "Medium",
            "attack_vector": "Dependência lenta causando degradação do serviço a montante",
            "vulnerability": "Sem circuit breakers, ausência de políticas de timeout, sem padrão bulkhead",
            "countermeasure": "Implementar circuit breakers (Hystrix/Resilience4j), definir timeouts em todas as chamadas de serviço, usar isolamento bulkhead",
            "cwe_reference": "CWE-400",
        },
    ],
    "container": [
        {
            "stride_letter": "E",
            "description": "Escape de container dá ao atacante acesso ao SO hospedeiro",
            "severity": "Critical",
            "attack_vector": "Exploração de container privilegiado, /proc/sysrq-trigger, socket do Docker exposto",
            "vulnerability": "Containers privilegiados, socket do daemon Docker exposto, execução como root",
            "countermeasure": "Rodar containers como non-root, usar sistema de arquivos raiz somente leitura, evitar modo privilegiado, usar gVisor/Kata containers",
            "cwe_reference": "CWE-269",
        },
        {
            "stride_letter": "T",
            "description": "Ataque de supply chain: imagem base ou dependência maliciosa injetada no container",
            "severity": "Critical",
            "attack_vector": "Typosquatting no registro de containers, imagem base comprometida",
            "vulnerability": "Uso de imagens públicas não verificadas, sem scanning de imagem no CI/CD",
            "countermeasure": "Escanear imagens com Trivy/Snyk, usar imagens base aprovadas, assinar imagens com Cosign, usar registro privado",
            "cwe_reference": "CWE-829",
        },
        {
            "stride_letter": "I",
            "description": "Segredos armazenados em variáveis de ambiente do container ou nas camadas da imagem",
            "severity": "High",
            "attack_vector": "Docker inspect, análise de camadas da imagem, vazamento de variável de ambiente",
            "vulnerability": "Segredos hardcoded no Dockerfile ou no ambiente, segredos no histórico da imagem",
            "countermeasure": "Usar gerenciador de segredos (Vault, AWS Secrets Manager), montar segredos em runtime, nunca embutir segredos nas imagens",
            "cwe_reference": "CWE-798",
        },
    ],
    "function": [
        {
            "stride_letter": "E",
            "description": "Role de execução da função com permissões excessivas permite acesso a recursos não previstos",
            "severity": "High",
            "attack_vector": "Exploração de role de IAM com privilégio excessivo anexada à Lambda/Function",
            "vulnerability": "Permissões com curinga (*) na role de execução da função, escalonamento de privilégio via IAM",
            "countermeasure": "Aplicar roles de IAM com privilégio mínimo por função, usar políticas baseadas em recurso, auditar permissões de função regularmente",
            "cwe_reference": "CWE-269",
        },
        {
            "stride_letter": "T",
            "description": "Injeção de evento: atacante controla os dados de gatilho da função para manipular a execução",
            "severity": "High",
            "attack_vector": "Injeção de payloads maliciosos via SQS, eventos S3, ou API Gateway na função",
            "vulnerability": "Ausência de validação de entrada nos dados do evento, deserialização sem sanitização",
            "countermeasure": "Validar e sanitizar todos os dados de payload do evento, usar validação de esquema, implementar autorização em nível de função",
            "cwe_reference": "CWE-20",
        },
        {
            "stride_letter": "D",
            "description": "Limite de concorrência da função esgotado por inundação de eventos, causando negação de serviço",
            "severity": "Medium",
            "attack_vector": "Inundação da fonte de eventos para esgotar os limites de concorrência",
            "vulnerability": "Limites de concorrência padrão, sem concorrência reservada para funções críticas",
            "countermeasure": "Definir concorrência reservada para funções críticas, implementar batching de SQS, usar políticas de throttling",
            "cwe_reference": "CWE-770",
        },
    ],
    "network": [
        {
            "stride_letter": "T",
            "description": "Tráfego de rede interceptado ou redirecionado via ARP spoofing ou sequestro de BGP",
            "severity": "High",
            "attack_vector": "Envenenamento de ARP na LAN, injeção de rota BGP",
            "vulnerability": "Topologia de rede plana, ausência de segmentação de rede",
            "countermeasure": "Implementar segmentação de rede com VPCs/subnets, usar subnets privadas para workloads sensíveis, habilitar VPC Flow Logs",
            "cwe_reference": "CWE-923",
        },
        {
            "stride_letter": "I",
            "description": "Tráfego de rede interno visível a serviços não autorizados por falta de segmentação",
            "severity": "Medium",
            "attack_vector": "Sniffing de tráfego leste-oeste dentro do mesmo segmento de rede",
            "vulnerability": "Ausência de políticas de rede, rede interna plana",
            "countermeasure": "Implementar micro-segmentação, usar grupos de segurança com privilégio mínimo, criptografar o tráfego leste-oeste",
            "cwe_reference": "CWE-311",
        },
    ],
    "external_service": [
        {
            "stride_letter": "T",
            "description": "Serviço de terceiros comprometido retorna dados maliciosos para a aplicação",
            "severity": "High",
            "attack_vector": "Ataque de supply chain na API externa, biblioteca de terceiros comprometida",
            "vulnerability": "Ausência de validação de resposta, confiança cega nos dados do serviço externo",
            "countermeasure": "Validar todas as respostas de serviços externos, usar validação de esquema, implementar circuit breakers para chamadas externas",
            "cwe_reference": "CWE-20",
        },
        {
            "stride_letter": "I",
            "description": "Dados sensíveis enviados a serviço externo ficam expostos a partes não autorizadas",
            "severity": "High",
            "attack_vector": "Vazamento de dados via integração de terceiros, exposição de chave de API",
            "vulnerability": "Compartilhamento excessivo de dados com serviços externos, credenciais de API vazadas",
            "countermeasure": "Minimizar os dados enviados a serviços externos, usar tokenização/pseudonimização, rotacionar chaves de API regularmente",
            "cwe_reference": "CWE-200",
        },
        {
            "stride_letter": "D",
            "description": "Aplicação indisponível por falha na dependência de serviço externo",
            "severity": "Medium",
            "attack_vector": "Indisponibilidade de terceiro, rate limiting pela API externa",
            "vulnerability": "Acoplamento forte com dependências externas, sem comportamento de fallback",
            "countermeasure": "Implementar degradação graciosa, usar circuit breakers e respostas de fallback, cachear respostas de serviços externos",
            "cwe_reference": "CWE-400",
        },
    ],
    "monitoring": [
        {
            "stride_letter": "R",
            "description": "Atacante apaga ou adultera logs para encobrir rastros após um comprometimento",
            "severity": "High",
            "attack_vector": "Exclusão de logs, injeção de log para ofuscar eventos maliciosos",
            "vulnerability": "Armazenamento de log mutável, ausência de proteção de integridade do log",
            "countermeasure": "Enviar logs para armazenamento imutável (WORM), usar streams de log append-only, implementar verificação de integridade dos logs",
            "cwe_reference": "CWE-778",
        },
        {
            "stride_letter": "I",
            "description": "Dados de monitoramento contêm PII sensível ou segredos expostos a consumidores de log não autorizados",
            "severity": "Medium",
            "attack_vector": "Logging excessivamente verboso incluindo senhas, tokens, PII",
            "vulnerability": "Sanitização insuficiente de log, acesso com privilégio excessivo aos dashboards de monitoramento",
            "countermeasure": "Implementar mascaramento de log para campos sensíveis, impor RBAC no acesso ao monitoramento, usar logging estruturado",
            "cwe_reference": "CWE-532",
        },
    ],
    "default": [
        {
            "stride_letter": "S",
            "description": "O componente pode ser personificado por um atacante sem autenticação adequada",
            "severity": "Medium",
            "attack_vector": "Spoofing de identidade, roubo de credenciais",
            "vulnerability": "Mecanismos de autenticação fracos ou ausentes",
            "countermeasure": "Implementar autenticação forte (MFA, baseada em certificado), validar identidade em toda requisição",
            "cwe_reference": "CWE-287",
        },
        {
            "stride_letter": "T",
            "description": "Dados processados ou armazenados por este componente podem ser adulterados",
            "severity": "Medium",
            "attack_vector": "Injeção de dados, man-in-the-middle",
            "vulnerability": "Ausência de verificação de integridade dos dados, canais não criptografados",
            "countermeasure": "Implementar validação de entrada, usar checksums/assinaturas digitais, criptografar dados em trânsito",
            "cwe_reference": "CWE-345",
        },
        {
            "stride_letter": "I",
            "description": "Informações sensíveis processadas por este componente podem ser expostas",
            "severity": "Medium",
            "attack_vector": "Exfiltração de dados, acesso não autorizado",
            "vulnerability": "Ausência de controles de acesso, armazenamento não criptografado",
            "countermeasure": "Aplicar acesso com privilégio mínimo, criptografar dados sensíveis em repouso e em trânsito",
            "cwe_reference": "CWE-200",
        },
        {
            "stride_letter": "D",
            "description": "Este componente pode ficar indisponível sob ataque ou carga elevada",
            "severity": "Medium",
            "attack_vector": "Esgotamento de recursos, DoS direcionado",
            "vulnerability": "Sem redundância, ausência de rate limiting",
            "countermeasure": "Implementar alta disponibilidade com redundância, aplicar rate limiting e auto-scaling",
            "cwe_reference": "CWE-400",
        },
        {
            "stride_letter": "E",
            "description": "Atacante pode explorar vulnerabilidades para obter privilégios elevados neste componente",
            "severity": "Medium",
            "attack_vector": "Escalonamento de privilégio via má configuração ou vulnerabilidade",
            "vulnerability": "Contas com privilégio excessivo, ausência de verificação de autorização",
            "countermeasure": "Aplicar o princípio do privilégio mínimo, implementar RBAC, auditar permissões regularmente",
            "cwe_reference": "CWE-269",
        },
    ],
}


def get_threats_for_component(component_type: str) -> List[dict]:
    """Retorna as ameaças STRIDE de um tipo de componente, usando o padrão como fallback."""
    threats = COMPONENT_STRIDE_THREATS.get(component_type, [])
    if not threats:
        threats = COMPONENT_STRIDE_THREATS["default"]
    return threats


def classify_component_type(component_name: str, component_description: str = "") -> str:
    """Casa o nome/descrição de um componente com um tipo conhecido usando correspondência de palavras-chave."""
    text = (component_name + " " + component_description).lower()
    scores: Dict[str, int] = {}
    for comp_type, keywords in COMPONENT_TYPE_KEYWORDS.items():
        score = sum(1 for kw in keywords if kw in text)
        if score:
            scores[comp_type] = score
    if not scores:
        return "application_server"
    return max(scores, key=scores.get)
