"""STRIDE threat modeling knowledge base — component types, threats, and countermeasures."""

from typing import Dict, List


COMPONENT_TYPES = {
    "user": "End user or external actor interacting with the system",
    "web_server": "HTTP/HTTPS web server serving content",
    "api_gateway": "API Gateway managing and routing API requests",
    "load_balancer": "Load balancer distributing traffic across servers",
    "application_server": "Backend application server processing business logic",
    "database": "Relational or NoSQL database storing data",
    "cache": "In-memory cache layer (Redis, ElastiCache, Memcached)",
    "message_queue": "Message broker for async communication (SQS, RabbitMQ, Kafka)",
    "authentication_service": "Authentication and authorization service (OAuth, SSO, IAM)",
    "cdn": "Content Delivery Network for static asset distribution",
    "firewall": "Network firewall or WAF filtering traffic",
    "storage": "File/object storage service (S3, Blob, GCS)",
    "microservice": "Individual microservice in a distributed architecture",
    "container": "Containerized workload (Docker, Kubernetes pod)",
    "function": "Serverless function (Lambda, Azure Functions)",
    "network": "Network boundary, VPC, subnet or DMZ",
    "external_service": "Third-party or external integration point",
    "monitoring": "Monitoring, logging, or observability service",
    "dns": "DNS service for name resolution",
    "vpn": "VPN or private tunnel endpoint",
}

COMPONENT_TYPE_KEYWORDS = {
    "user": ["user", "client", "browser", "developer", "admin", "actor", "person", "operator"],
    "web_server": ["web server", "nginx", "apache", "iis", "httpd", "http server"],
    "api_gateway": ["api gateway", "api management", "apigee", "kong", "api manager", "gateway"],
    "load_balancer": ["load balancer", "alb", "elb", "nlb", "application load", "balancer"],
    "application_server": ["app server", "application server", "backend", "server", "sei", "sip", "application"],
    "database": ["database", "rds", "mysql", "postgres", "mongodb", "dynamodb", "sql", "nosql", "db"],
    "cache": ["cache", "redis", "elasticache", "memcached", "in-memory"],
    "message_queue": ["queue", "sqs", "sns", "kafka", "rabbitmq", "message broker", "pubsub"],
    "authentication_service": ["auth", "authentication", "iam", "sso", "oauth", "microsoft entra", "entra", "identity", "ad", "active directory"],
    "cdn": ["cdn", "cloudfront", "cloudflare", "fastly", "akamai", "content delivery"],
    "firewall": ["firewall", "waf", "shield", "ddos", "security group", "aws waf", "aws shield"],
    "storage": ["storage", "s3", "blob", "efs", "nfs", "file system", "object storage", "elastic file"],
    "microservice": ["microservice", "service", "logic app", "workflow"],
    "container": ["container", "docker", "kubernetes", "k8s", "ecs", "pod"],
    "function": ["lambda", "function", "serverless", "azure function", "cloud function"],
    "network": ["vpc", "vnet", "subnet", "network", "availability zone", "private subnet", "public subnet", "resource group"],
    "external_service": ["saas", "rest", "soap", "third-party", "external", "web service", "azure services"],
    "monitoring": ["cloudwatch", "monitoring", "logging", "cloudtrail", "audit", "log", "alerting"],
    "dns": ["dns", "route53", "name server"],
    "vpn": ["vpn", "tunnel", "private connection", "expressroute"],
}

STRIDE_CATEGORIES = {
    "S": {
        "name": "Spoofing",
        "description": "Impersonating something or someone else",
        "property_violated": "Authentication",
        "color": "#e74c3c",
    },
    "T": {
        "name": "Tampering",
        "description": "Modifying data or code",
        "property_violated": "Integrity",
        "color": "#e67e22",
    },
    "R": {
        "name": "Repudiation",
        "description": "Claiming not to have performed an action",
        "property_violated": "Non-repudiation",
        "color": "#f1c40f",
    },
    "I": {
        "name": "Information Disclosure",
        "description": "Exposing information to unauthorized parties",
        "property_violated": "Confidentiality",
        "color": "#3498db",
    },
    "D": {
        "name": "Denial of Service",
        "description": "Deny or degrade service to users",
        "property_violated": "Availability",
        "color": "#9b59b6",
    },
    "E": {
        "name": "Elevation of Privilege",
        "description": "Gain capabilities without authorization",
        "property_violated": "Authorization",
        "color": "#27ae60",
    },
}

COMPONENT_STRIDE_THREATS: Dict[str, List[dict]] = {
    "user": [
        {
            "stride_letter": "S",
            "description": "Attacker impersonates a legitimate user to access the system",
            "severity": "High",
            "attack_vector": "Credential theft, phishing, session hijacking",
            "vulnerability": "Weak authentication, password reuse, missing MFA",
            "countermeasure": "Implement multi-factor authentication (MFA), enforce strong password policies, use FIDO2/WebAuthn",
            "cwe_reference": "CWE-287",
        },
        {
            "stride_letter": "R",
            "description": "User denies performing a sensitive action (e.g., transaction, data change)",
            "severity": "Medium",
            "attack_vector": "Lack of audit trails, unsigned actions",
            "vulnerability": "Missing audit logging, no digital signatures",
            "countermeasure": "Implement centralized audit logging with tamper-proof storage, use digital signatures for critical actions",
            "cwe_reference": "CWE-778",
        },
        {
            "stride_letter": "I",
            "description": "User's personal data or session token is exposed",
            "severity": "High",
            "attack_vector": "Man-in-the-middle attack, insecure storage of tokens",
            "vulnerability": "Unencrypted channels, insecure local storage",
            "countermeasure": "Enforce HTTPS/TLS everywhere, store tokens in httpOnly secure cookies, implement token rotation",
            "cwe_reference": "CWE-311",
        },
    ],
    "web_server": [
        {
            "stride_letter": "T",
            "description": "Attacker modifies HTTP responses or injects malicious content (XSS, response injection)",
            "severity": "High",
            "attack_vector": "Cross-site scripting (XSS), HTTP response splitting",
            "vulnerability": "Lack of output encoding, missing Content Security Policy",
            "countermeasure": "Implement strict Content Security Policy (CSP), encode all user output, use security headers (X-Frame-Options, HSTS)",
            "cwe_reference": "CWE-79",
        },
        {
            "stride_letter": "D",
            "description": "Web server overwhelmed by DDoS attack, making it unavailable",
            "severity": "High",
            "attack_vector": "Volumetric DDoS, HTTP flood, Slowloris attack",
            "vulnerability": "No rate limiting, no DDoS protection layer",
            "countermeasure": "Use WAF and DDoS protection (CloudFlare, AWS Shield), implement rate limiting and connection throttling",
            "cwe_reference": "CWE-400",
        },
        {
            "stride_letter": "I",
            "description": "Server configuration files, stack traces, or sensitive data exposed through error pages or directory listing",
            "severity": "Medium",
            "attack_vector": "Forced browsing, error message analysis",
            "vulnerability": "Verbose error messages, enabled directory listing, misconfigured server",
            "countermeasure": "Disable directory listing, use generic error pages, remove server version headers",
            "cwe_reference": "CWE-200",
        },
        {
            "stride_letter": "E",
            "description": "Attacker exploits web server vulnerability to gain elevated OS-level privileges",
            "severity": "Critical",
            "attack_vector": "Remote code execution via unpatched CVE, file upload exploitation",
            "vulnerability": "Unpatched server software, insecure file upload handling",
            "countermeasure": "Keep server software updated, implement least-privilege execution, use container isolation",
            "cwe_reference": "CWE-269",
        },
    ],
    "api_gateway": [
        {
            "stride_letter": "S",
            "description": "Attacker forges API tokens or API keys to access protected endpoints",
            "severity": "Critical",
            "attack_vector": "API key theft, JWT forgery, OAuth token abuse",
            "vulnerability": "Weak token validation, insecure key storage, missing signature verification",
            "countermeasure": "Validate JWT signatures, use short-lived tokens with refresh rotation, implement API key scoping",
            "cwe_reference": "CWE-347",
        },
        {
            "stride_letter": "T",
            "description": "Attacker intercepts and modifies API requests in transit",
            "severity": "High",
            "attack_vector": "Man-in-the-middle attack on API calls",
            "vulnerability": "Missing TLS, no request/response signing",
            "countermeasure": "Enforce TLS 1.2+ for all API traffic, implement request signing (HMAC), use mTLS for service-to-service",
            "cwe_reference": "CWE-319",
        },
        {
            "stride_letter": "D",
            "description": "API overwhelmed by excessive requests (API flooding)",
            "severity": "High",
            "attack_vector": "API abuse, bot attacks, scraping at scale",
            "vulnerability": "Missing rate limiting, no throttling policies",
            "countermeasure": "Implement rate limiting and quota management per API key/user, use API gateway throttling",
            "cwe_reference": "CWE-770",
        },
        {
            "stride_letter": "E",
            "description": "Broken object-level authorization (BOLA/IDOR) allows access to other users' resources",
            "severity": "Critical",
            "attack_vector": "Manipulating object IDs in API requests (IDOR/BOLA — OWASP API #1)",
            "vulnerability": "Missing authorization checks at resource level",
            "countermeasure": "Implement object-level authorization checks, use indirect references, enforce ownership validation",
            "cwe_reference": "CWE-639",
        },
    ],
    "load_balancer": [
        {
            "stride_letter": "T",
            "description": "Attacker manipulates routing rules to redirect traffic to malicious backends",
            "severity": "High",
            "attack_vector": "Misconfigured routing, DNS poisoning",
            "vulnerability": "Unprotected admin interface, no routing rule integrity checks",
            "countermeasure": "Restrict admin access to management plane, enforce IaC-based configuration, enable change auditing",
            "cwe_reference": "CWE-601",
        },
        {
            "stride_letter": "D",
            "description": "Load balancer becomes single point of failure under heavy attack",
            "severity": "High",
            "attack_vector": "DDoS targeting load balancer, session table exhaustion",
            "vulnerability": "Single load balancer instance, no auto-scaling",
            "countermeasure": "Deploy load balancers in HA pairs across availability zones, use anycast for global distribution",
            "cwe_reference": "CWE-400",
        },
        {
            "stride_letter": "I",
            "description": "TLS termination at load balancer exposes plaintext traffic on the internal network",
            "severity": "Medium",
            "attack_vector": "Internal network sniffing after TLS termination",
            "vulnerability": "TLS termination without re-encryption to backends",
            "countermeasure": "Use end-to-end TLS or TLS passthrough, encrypt internal traffic between load balancer and backends",
            "cwe_reference": "CWE-311",
        },
    ],
    "application_server": [
        {
            "stride_letter": "T",
            "description": "SQL/NoSQL injection allows attacker to modify database queries and data",
            "severity": "Critical",
            "attack_vector": "SQL injection, command injection via unsanitized user input",
            "vulnerability": "Dynamic query construction with user input, missing parameterized queries",
            "countermeasure": "Use parameterized queries/prepared statements, implement ORM with query binding, apply input validation",
            "cwe_reference": "CWE-89",
        },
        {
            "stride_letter": "E",
            "description": "Insecure deserialization leads to remote code execution",
            "severity": "Critical",
            "attack_vector": "Crafted serialized objects in API payloads",
            "vulnerability": "Deserializing untrusted data without integrity checks",
            "countermeasure": "Avoid deserialization of untrusted data, use allow-lists for deserialization, implement integrity verification",
            "cwe_reference": "CWE-502",
        },
        {
            "stride_letter": "I",
            "description": "Sensitive data leaked through verbose logs or debug endpoints left in production",
            "severity": "Medium",
            "attack_vector": "Log injection, exposed debug endpoints, SSRF",
            "vulnerability": "Debug mode in production, PII in logs, SSRF vulnerabilities",
            "countermeasure": "Disable debug mode in production, redact PII from logs, block SSRF with metadata endpoint protection",
            "cwe_reference": "CWE-532",
        },
        {
            "stride_letter": "D",
            "description": "Application consumes unbounded resources due to algorithmic complexity attack (ReDoS, zip bomb)",
            "severity": "Medium",
            "attack_vector": "ReDoS (regex denial of service), large payload uploads, zip bombs",
            "vulnerability": "Unbounded regex, missing payload size limits",
            "countermeasure": "Set payload size limits, use safe regex libraries, implement circuit breakers",
            "cwe_reference": "CWE-407",
        },
    ],
    "database": [
        {
            "stride_letter": "T",
            "description": "Attacker modifies or deletes data directly in the database",
            "severity": "Critical",
            "attack_vector": "SQL injection, unauthorized direct database access",
            "vulnerability": "Exposed database port, overprivileged application accounts",
            "countermeasure": "Restrict DB to private subnets only, use least-privilege DB accounts, enable row-level security",
            "cwe_reference": "CWE-89",
        },
        {
            "stride_letter": "I",
            "description": "Database dump exposes sensitive customer data (PII, credentials, financial data)",
            "severity": "Critical",
            "attack_vector": "Data exfiltration via SQL injection, backup theft, misconfigured access",
            "vulnerability": "Unencrypted storage, overly permissive IAM policies, unencrypted backups",
            "countermeasure": "Enable encryption at rest and in transit, implement column-level encryption for PII, restrict backup access",
            "cwe_reference": "CWE-312",
        },
        {
            "stride_letter": "D",
            "description": "Database unavailable due to resource exhaustion or ransomware attack",
            "severity": "High",
            "attack_vector": "Connection pool exhaustion, ransomware encrypting data files",
            "vulnerability": "No connection limits, unprotected backup retention",
            "countermeasure": "Set connection pool limits, implement PITR backups, use Multi-AZ for high availability",
            "cwe_reference": "CWE-400",
        },
        {
            "stride_letter": "E",
            "description": "Database user escalates privileges to DBA/root via stored procedure exploitation",
            "severity": "High",
            "attack_vector": "Exploiting stored procedures with EXECUTE AS, UDF injection",
            "vulnerability": "Overprivileged DB users, unaudited stored procedures",
            "countermeasure": "Principle of least privilege for all DB accounts, audit all stored procedures, disable xp_cmdshell",
            "cwe_reference": "CWE-269",
        },
        {
            "stride_letter": "R",
            "description": "Database changes performed without audit trail, preventing forensic investigation",
            "severity": "Medium",
            "attack_vector": "Insider threat, untracked schema/data changes",
            "vulnerability": "Missing audit logging, no change data capture",
            "countermeasure": "Enable database audit logging, use CDC (Change Data Capture), store logs in immutable storage",
            "cwe_reference": "CWE-778",
        },
    ],
    "cache": [
        {
            "stride_letter": "T",
            "description": "Cache poisoning attack injects malicious data into the cache, served to legitimate users",
            "severity": "High",
            "attack_vector": "HTTP response splitting, cache key manipulation",
            "vulnerability": "Improper cache key construction, missing cache validation",
            "countermeasure": "Use strict cache key policies, validate cache entries, implement cache-busting for sensitive data",
            "cwe_reference": "CWE-349",
        },
        {
            "stride_letter": "I",
            "description": "Sensitive data cached in plaintext and accessible to unauthorized services",
            "severity": "High",
            "attack_vector": "Unauthorized access to Redis/Memcached without authentication",
            "vulnerability": "Cache exposed without authentication (default Redis config), no network isolation",
            "countermeasure": "Enable Redis AUTH, bind to private interfaces only, avoid caching sensitive data without encryption",
            "cwe_reference": "CWE-312",
        },
        {
            "stride_letter": "D",
            "description": "Cache stampede overwhelms backend when cache expires simultaneously",
            "severity": "Medium",
            "attack_vector": "Thundering herd, cache invalidation attacks",
            "vulnerability": "No cache lock/mutex, simultaneous expiry of hot keys",
            "countermeasure": "Implement cache lock/mutex pattern, use probabilistic early expiration, set staggered TTLs",
            "cwe_reference": "CWE-400",
        },
    ],
    "message_queue": [
        {
            "stride_letter": "T",
            "description": "Attacker injects malicious messages into the queue to manipulate downstream processing",
            "severity": "High",
            "attack_vector": "Message injection via compromised producer, replay attacks",
            "vulnerability": "Missing message integrity checks, no authentication on producers",
            "countermeasure": "Sign messages with HMAC/digital signatures, validate message schemas, implement dead-letter queues",
            "cwe_reference": "CWE-20",
        },
        {
            "stride_letter": "R",
            "description": "Message sender denies publishing a message, no proof of origin",
            "severity": "Medium",
            "attack_vector": "Disavowal of message delivery in financial/compliance workflows",
            "vulnerability": "No message signing, missing correlation IDs",
            "countermeasure": "Use message signing with asymmetric keys, implement message receipts, enable audit trail",
            "cwe_reference": "CWE-778",
        },
        {
            "stride_letter": "D",
            "description": "Queue flooded with poison pill messages causing consumer crashes (DoS)",
            "severity": "High",
            "attack_vector": "Message flooding, poison pill pattern",
            "vulnerability": "No rate limiting on message ingestion, missing dead-letter queue",
            "countermeasure": "Implement dead-letter queues, set message size/rate limits, use consumer circuit breakers",
            "cwe_reference": "CWE-400",
        },
        {
            "stride_letter": "I",
            "description": "Messages in transit contain unencrypted sensitive payload data",
            "severity": "High",
            "attack_vector": "Network sniffing, unauthorized queue listener subscription",
            "vulnerability": "Unencrypted message payloads, no access control on queue subscriptions",
            "countermeasure": "Encrypt message payloads at application level, restrict queue access via IAM policies",
            "cwe_reference": "CWE-311",
        },
    ],
    "authentication_service": [
        {
            "stride_letter": "S",
            "description": "Attacker bypasses authentication via OAuth/SAML misconfiguration or token forgery",
            "severity": "Critical",
            "attack_vector": "OAuth implicit flow abuse, SAML assertion forgery, JWT algorithm confusion (alg:none)",
            "vulnerability": "Misconfigured OAuth flows, weak SAML validation, accepting unsigned JWTs",
            "countermeasure": "Use PKCE for OAuth, validate all SAML assertions, enforce RS256/ES256 JWT signing, reject alg:none",
            "cwe_reference": "CWE-287",
        },
        {
            "stride_letter": "E",
            "description": "Privilege escalation via scope manipulation or role assignment vulnerability",
            "severity": "Critical",
            "attack_vector": "Scope elevation in OAuth, mass assignment in user profile, forced browsing to admin endpoints",
            "vulnerability": "Improper scope validation, mass assignment vulnerability in user object",
            "countermeasure": "Validate scopes server-side on every request, use allowlists for role assignment, implement ABAC/RBAC",
            "cwe_reference": "CWE-269",
        },
        {
            "stride_letter": "D",
            "description": "Authentication service unavailable due to credential stuffing attack or infrastructure failure",
            "severity": "High",
            "attack_vector": "Credential stuffing, brute force causing account lockout, infrastructure DDoS",
            "vulnerability": "No lockout thresholds, no bot protection, single auth instance",
            "countermeasure": "Implement account lockout with CAPTCHA, use CAPTCHA for failed logins, deploy auth in HA configuration",
            "cwe_reference": "CWE-307",
        },
        {
            "stride_letter": "I",
            "description": "Credentials or tokens exposed in logs, URLs, or error messages",
            "severity": "High",
            "attack_vector": "Log analysis, referrer header leakage, debug endpoints",
            "vulnerability": "Logging sensitive data, passing credentials in URL parameters",
            "countermeasure": "Never log credentials/tokens, pass tokens via headers not URLs, scrub PII from all logs",
            "cwe_reference": "CWE-532",
        },
    ],
    "cdn": [
        {
            "stride_letter": "T",
            "description": "CDN cache poisoning serves malicious content to users globally",
            "severity": "High",
            "attack_vector": "HTTP host header injection, cache key manipulation",
            "vulnerability": "Improper cache key normalization, missing cache validation",
            "countermeasure": "Configure strict cache keys, implement Vary headers, use cache-control no-store for sensitive pages",
            "cwe_reference": "CWE-349",
        },
        {
            "stride_letter": "D",
            "description": "CDN origin servers overwhelmed when CDN is bypassed",
            "severity": "Medium",
            "attack_vector": "Direct origin IP targeting after CDN IP discovery",
            "vulnerability": "Exposed origin IP, no origin firewall to restrict non-CDN traffic",
            "countermeasure": "Restrict origin to CDN IP ranges only, rotate/hide origin IP, implement origin shield",
            "cwe_reference": "CWE-400",
        },
    ],
    "firewall": [
        {
            "stride_letter": "T",
            "description": "Firewall rules misconfigured to allow unauthorized traffic through",
            "severity": "Critical",
            "attack_vector": "Rule misconfiguration, infrastructure drift, overly permissive 0.0.0.0/0 rules",
            "vulnerability": "Manual rule management, missing infrastructure-as-code enforcement",
            "countermeasure": "Use IaC for all firewall rules, enforce least-privilege network access, regular security group audits",
            "cwe_reference": "CWE-183",
        },
        {
            "stride_letter": "E",
            "description": "Attacker bypasses WAF using encoding tricks to reach vulnerable backend",
            "severity": "High",
            "attack_vector": "WAF bypass via Unicode encoding, double encoding, HTTP parameter pollution",
            "vulnerability": "Regex-based WAF rules without normalization, incomplete rule coverage",
            "countermeasure": "Use managed WAF rule groups, normalize input before WAF evaluation, keep WAF rules updated",
            "cwe_reference": "CWE-20",
        },
    ],
    "storage": [
        {
            "stride_letter": "I",
            "description": "Publicly accessible storage bucket exposes sensitive files",
            "severity": "Critical",
            "attack_vector": "S3 bucket enumeration, public ACL misconfiguration",
            "vulnerability": "Public bucket policies, missing Block Public Access setting",
            "countermeasure": "Enable Block Public Access, use bucket policies to deny public access, enable S3 server-side encryption",
            "cwe_reference": "CWE-312",
        },
        {
            "stride_letter": "T",
            "description": "Attacker overwrites or deletes critical files in storage",
            "severity": "High",
            "attack_vector": "Overprivileged IAM role with s3:DeleteObject, ransomware",
            "vulnerability": "Overprivileged storage access, missing versioning and MFA delete",
            "countermeasure": "Enable object versioning with MFA delete, use least-privilege IAM, implement S3 Object Lock for compliance",
            "cwe_reference": "CWE-732",
        },
        {
            "stride_letter": "D",
            "description": "Storage unavailable due to accidental deletion or ransomware",
            "severity": "High",
            "attack_vector": "Accidental `rm -rf`, ransomware encryption of shared file system",
            "vulnerability": "No backup strategy, no soft-delete or versioning",
            "countermeasure": "Enable versioning and cross-region replication, implement automated backups with tested restore procedures",
            "cwe_reference": "CWE-400",
        },
    ],
    "microservice": [
        {
            "stride_letter": "S",
            "description": "Attacker impersonates a trusted internal service to make unauthorized calls",
            "severity": "High",
            "attack_vector": "Missing service-to-service authentication, stolen service credentials",
            "vulnerability": "Services accepting calls from any internal IP without authentication",
            "countermeasure": "Implement mutual TLS (mTLS) for service-to-service communication, use service mesh with identity (Istio/Linkerd)",
            "cwe_reference": "CWE-287",
        },
        {
            "stride_letter": "T",
            "description": "Malicious microservice in the mesh injects tampered responses",
            "severity": "High",
            "attack_vector": "Compromised sidecar proxy, supply chain attack on service image",
            "vulnerability": "Unsigned container images, lack of network policy enforcement",
            "countermeasure": "Sign all container images (Cosign/Notary), enforce network policies, use service mesh for traffic encryption",
            "cwe_reference": "CWE-829",
        },
        {
            "stride_letter": "D",
            "description": "Cascading failures across microservices due to missing circuit breakers",
            "severity": "Medium",
            "attack_vector": "Slow dependency causing upstream service degradation",
            "vulnerability": "No circuit breakers, missing timeout policies, no bulkhead pattern",
            "countermeasure": "Implement circuit breakers (Hystrix/Resilience4j), set timeouts on all service calls, use bulkhead isolation",
            "cwe_reference": "CWE-400",
        },
    ],
    "container": [
        {
            "stride_letter": "E",
            "description": "Container escape gives attacker access to the host OS",
            "severity": "Critical",
            "attack_vector": "Privileged container exploit, /proc/sysrq-trigger, exposed Docker socket",
            "vulnerability": "Privileged containers, exposed Docker daemon socket, running as root",
            "countermeasure": "Run containers as non-root, use read-only root filesystem, avoid privileged mode, use gVisor/Kata containers",
            "cwe_reference": "CWE-269",
        },
        {
            "stride_letter": "T",
            "description": "Supply chain attack: malicious base image or dependency injected in container",
            "severity": "Critical",
            "attack_vector": "Typosquatting on container registry, compromised base image",
            "vulnerability": "Using unverified public images, no image scanning in CI/CD",
            "countermeasure": "Scan images with Trivy/Snyk, use approved base images, sign images with Cosign, use private registry",
            "cwe_reference": "CWE-829",
        },
        {
            "stride_letter": "I",
            "description": "Secrets stored in container environment variables or image layers",
            "severity": "High",
            "attack_vector": "Docker inspect, image layer analysis, env var leakage",
            "vulnerability": "Hardcoded secrets in Dockerfile or environment, secrets in image history",
            "countermeasure": "Use secrets manager (Vault, AWS Secrets Manager), mount secrets at runtime, never bake secrets into images",
            "cwe_reference": "CWE-798",
        },
    ],
    "function": [
        {
            "stride_letter": "E",
            "description": "Over-permissive function execution role allows access to unintended resources",
            "severity": "High",
            "attack_vector": "Exploiting overprivileged IAM role attached to Lambda/Function",
            "vulnerability": "Star (*) permissions in function execution role, IAM privilege escalation",
            "countermeasure": "Apply least-privilege IAM roles per function, use resource-based policies, regularly audit function permissions",
            "cwe_reference": "CWE-269",
        },
        {
            "stride_letter": "T",
            "description": "Event injection: attacker controls function trigger data to manipulate execution",
            "severity": "High",
            "attack_vector": "Injecting malicious payloads via SQS, S3 events, or API Gateway into function",
            "vulnerability": "Missing input validation on event data, deserialization without sanitization",
            "countermeasure": "Validate and sanitize all event payload data, use schema validation, implement function-level authorization",
            "cwe_reference": "CWE-20",
        },
        {
            "stride_letter": "D",
            "description": "Function concurrency limit exhausted by event flood, causing denial of service",
            "severity": "Medium",
            "attack_vector": "Flooding event source to exhaust concurrency limits",
            "vulnerability": "Default concurrency limits, no reserved concurrency for critical functions",
            "countermeasure": "Set reserved concurrency for critical functions, implement SQS batching, use throttling policies",
            "cwe_reference": "CWE-770",
        },
    ],
    "network": [
        {
            "stride_letter": "T",
            "description": "Network traffic intercepted or redirected via ARP spoofing or BGP hijacking",
            "severity": "High",
            "attack_vector": "ARP poisoning on LAN, BGP route injection",
            "vulnerability": "Flat network topology, missing network segmentation",
            "countermeasure": "Implement network segmentation with VPCs/subnets, use private subnets for sensitive workloads, enable VPC Flow Logs",
            "cwe_reference": "CWE-923",
        },
        {
            "stride_letter": "I",
            "description": "Internal network traffic visible to unauthorized services due to lack of segmentation",
            "severity": "Medium",
            "attack_vector": "East-west traffic sniffing within the same network segment",
            "vulnerability": "Missing network policies, flat internal network",
            "countermeasure": "Implement micro-segmentation, use security groups with least-privilege, encrypt east-west traffic",
            "cwe_reference": "CWE-311",
        },
    ],
    "external_service": [
        {
            "stride_letter": "T",
            "description": "Third-party service compromised and returns malicious data to the application",
            "severity": "High",
            "attack_vector": "Supply chain attack on external API, compromised third-party library",
            "vulnerability": "Missing response validation, blind trust of external service data",
            "countermeasure": "Validate all external service responses, use schema validation, implement circuit breakers for external calls",
            "cwe_reference": "CWE-20",
        },
        {
            "stride_letter": "I",
            "description": "Sensitive data sent to external service and exposed to unauthorized parties",
            "severity": "High",
            "attack_vector": "Data leakage via third-party integration, API key exposure",
            "vulnerability": "Over-sharing of data with external services, leaked API credentials",
            "countermeasure": "Minimize data sent to external services, use tokenization/pseudonymization, rotate API keys regularly",
            "cwe_reference": "CWE-200",
        },
        {
            "stride_letter": "D",
            "description": "Application unavailable due to external service dependency failure",
            "severity": "Medium",
            "attack_vector": "Third-party outage, rate limiting by external API",
            "vulnerability": "Tight coupling to external dependencies, no fallback behavior",
            "countermeasure": "Implement graceful degradation, use circuit breakers and fallback responses, cache external service responses",
            "cwe_reference": "CWE-400",
        },
    ],
    "monitoring": [
        {
            "stride_letter": "R",
            "description": "Attacker clears or tampers with logs to cover tracks after compromise",
            "severity": "High",
            "attack_vector": "Log deletion, log injection to obfuscate malicious events",
            "vulnerability": "Mutable log storage, missing log integrity protection",
            "countermeasure": "Send logs to immutable storage (WORM), use append-only log streams, implement log integrity verification",
            "cwe_reference": "CWE-778",
        },
        {
            "stride_letter": "I",
            "description": "Monitoring data contains sensitive PII or secrets exposed to unauthorized log consumers",
            "severity": "Medium",
            "attack_vector": "Overly verbose logging includes passwords, tokens, PII",
            "vulnerability": "Insufficient log sanitization, overprivileged access to monitoring dashboards",
            "countermeasure": "Implement log masking for sensitive fields, enforce RBAC on monitoring access, use structured logging",
            "cwe_reference": "CWE-532",
        },
    ],
    "default": [
        {
            "stride_letter": "S",
            "description": "Component may be impersonated by an attacker lacking proper authentication",
            "severity": "Medium",
            "attack_vector": "Identity spoofing, credential theft",
            "vulnerability": "Weak or missing authentication mechanisms",
            "countermeasure": "Implement strong authentication (MFA, certificate-based), validate identity on every request",
            "cwe_reference": "CWE-287",
        },
        {
            "stride_letter": "T",
            "description": "Data processed or stored by this component may be tampered with",
            "severity": "Medium",
            "attack_vector": "Data injection, man-in-the-middle",
            "vulnerability": "Lack of data integrity checks, unencrypted channels",
            "countermeasure": "Implement input validation, use checksums/digital signatures, encrypt data in transit",
            "cwe_reference": "CWE-345",
        },
        {
            "stride_letter": "I",
            "description": "Sensitive information processed by this component may be exposed",
            "severity": "Medium",
            "attack_vector": "Data exfiltration, unauthorized access",
            "vulnerability": "Missing access controls, unencrypted storage",
            "countermeasure": "Apply least-privilege access, encrypt sensitive data at rest and in transit",
            "cwe_reference": "CWE-200",
        },
        {
            "stride_letter": "D",
            "description": "This component may become unavailable under attack or high load",
            "severity": "Medium",
            "attack_vector": "Resource exhaustion, targeted DoS",
            "vulnerability": "No redundancy, missing rate limiting",
            "countermeasure": "Implement high availability with redundancy, apply rate limiting and auto-scaling",
            "cwe_reference": "CWE-400",
        },
        {
            "stride_letter": "E",
            "description": "Attacker may exploit vulnerabilities to gain elevated privileges on this component",
            "severity": "Medium",
            "attack_vector": "Privilege escalation via misconfiguration or vulnerability",
            "vulnerability": "Overprivileged accounts, missing authorization checks",
            "countermeasure": "Apply principle of least privilege, implement RBAC, regularly audit permissions",
            "cwe_reference": "CWE-269",
        },
    ],
}


def get_threats_for_component(component_type: str) -> List[dict]:
    """Return STRIDE threats for a given component type, falling back to defaults."""
    threats = COMPONENT_STRIDE_THREATS.get(component_type, [])
    if not threats:
        threats = COMPONENT_STRIDE_THREATS["default"]
    return threats


def classify_component_type(component_name: str, component_description: str = "") -> str:
    """Match a component name/description to a known type using keyword matching."""
    text = (component_name + " " + component_description).lower()
    scores: Dict[str, int] = {}
    for comp_type, keywords in COMPONENT_TYPE_KEYWORDS.items():
        score = sum(1 for kw in keywords if kw in text)
        if score:
            scores[comp_type] = score
    if not scores:
        return "application_server"
    return max(scores, key=scores.get)
